package com.ironman.model;

public enum NotificationType {
    ORDER_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PICKUP_ASSIGNED,
    PICKUP_ACCEPTED,
    PICKUP_COMPLETED,
    ORDER_PROCESSING,
    READY_FOR_DELIVERY,
    DELIVERY_ASSIGNED,
    DELIVERY_ACCEPTED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    ORDER_CANCELLED,
    PARTNER_APPROVED,
    PARTNER_REJECTED,
    ASSIGNMENT_NEW,
    ASSIGNMENT_CANCELLED
}